version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: course-management-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: course-management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - course-management-network

  # Backend API
  backend:
    build: .
    container_name: course-management-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/course-management?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - course-management-network

  # Frontend Application
  frontend:
    build: ./frontend
    container_name: course-management-ui
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - course-management-network

volumes:
  mongodb_data:

networks:
  course-management-network:
    driver: bridge 